shura.datasource:
  url: jdbc:sqlite:shura.db
  driver: org.sqlite.JDBC

hibernate.dialect: org.hibernate.dialect.SQLiteDialect
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging.level:
  root: INFO
  org.hibernate: ERROR

discord:
  token:

shura:
  drunk-mode: true
  thresh-hold: 3